baseurl = "/"
title = "Zarchive"
languageCode = "en-us"
theme = "archie"
copyright = "© John Christopher Zander (content)."

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  author = "Z Man"
  description = "Archive of the timeless writings of Z Man, Christopher Zeeman, John Christopher Zander, RIP."
  custom_css = ["css/custom.css"]
  custom_scss = ["scss/custom.scss"]

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "Read"
  url = "/read/"
  weight = 1

[[menu.main]]
  name = "Watch"
  url = "/watch/"
  weight = 2

[[menu.main]]
  name = "Listen"
  url = "/listen/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[author]
  name = "Z Man"

[taxonomies]
  category = "categories"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
