baseurl = "https://friendsofzman.com"
title = "Zarchive"
languageCode = "en-us"
theme = "archie"
copyright = "© John Christopher Zander (content) & Novo Press (website)."

[params]
  copyright = "Z Man. Site by Novo Press."
  description = "Archive of the timeless writings of Z Man, Christopher Zeeman, John Christopher Zander, RIP."
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files

[pagination]
  pagerSize = 10

[[menu.main]]
  name = "Read"
  url = "/read/"
  weight = 1

[[menu.main]]
  name = "Watch"
  url = "/watch/"
  weight = 2

[[menu.main]]
  name = "Listen"
  url = "/listen/"
  weight = 3

[[menu.main]]
  name = "Memoriam"
  url = "/memoriam/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5

[author]
  name = "Z Man"

[taxonomies]
  category = "categories"

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2
